version: "3.8"

services:
  python_executor:
    build:
      context: ./python_executor
    container_name: python_executor
    ports:
      - "8001:8080"
    restart: unless-stopped

  js_executor:
    build:
      context: ./js_executor
    container_name: js_executor
    ports:
      - "8002:8080"
    restart: unless-stopped

  cpp_executor:
    build:
      context: ./cpp_executor
    container_name: cpp_executor
    ports:
      - "8003:8080"
    restart: unless-stopped

  java_executor:
    build:
      context: ./java_executor
    container_name: java_executor
    ports:
      - "8004:8080"
    restart: unless-stopped 